### ISSUE TITLE
Error in import Universe

### ISSUE THREAD

**Issue by Martellacci** [harinij/100DaysOfCode#2]
When I launch python gamebot_basiv.py i obtain the follow error:

Thanks for your help.
Marco

python gamebot.py
Traceback (most recent call last):
  File "gamebot.py", line 2, in <module>
    import universe # register the universe environments
  File "/Users/marco/openai/test2/lib/python3.6/site-packages/universe/__init__.py", line 22, in <module>
    from universe import error, envs
  File "/Users/marco/openai/test2/lib/python3.6/site-packages/universe/envs/__init__.py", line 1, in <module>
    import universe.envs.vnc_env
  File "/Users/marco/openai/test2/lib/python3.6/site-packages/universe/envs/vnc_env.py", line 11, in <module>
    from universe.envs import diagnostics
  File "/Users/marco/openai/test2/lib/python3.6/site-packages/universe/envs/diagnostics.py", line 2, in <module>
    import fastzbarlight
  File "/Users/marco/openai/test2/lib/python3.6/site-packages/fastzbarlight/__init__.py", line 7, in <module>
    from ._zbarlight import zbar_code_scanner
ImportError: dlopen(/Users/marco/openai/test2/lib/python3.6/site-packages/fastzbarlight/_zbarlight.cpython-36m-darwin.so, 2): Symbol not found: _iconv
  Referenced from: /Users/marco/openai/test2/lib/python3.6/site-packages/fastzbarlight/_zbarlight.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/marco/openai/test2/lib/python3.6/site-packages/fastzbarlight/_zbarlight.cpython-36m-darwin.so

**Comment by harinij** [comment]
The solution for this is mentioned here: https://github.com/openai/universe/issues/139#issuecomment-289441706
