### ISSUE TITLE
Can't start the script - Permission denied

### ISSUE THREAD

**Issue by Dominik1999** [harinij/100DaysOfCode#4]
Hey, thank you so much for the nice tutorial. Unfortunately I get the following error message when I try to start the script:
```
/home/dominik/PycharmProjects/GymAI/.ai/bin/python /home/dominik/.PyCharmCE2018.2/config/scratches/test_ai.py
[2018-11-15 16:19:49,089] Making new env: flashgames.NeonRace-v0
[2018-11-15 16:19:49,099] Writing logs to file: /tmp/universe-10221.log
Traceback (most recent call last):
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/docker/transport/unixconn.py", line 33, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py", line 255, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/docker/transport/unixconn.py", line 33, in connect
    sock.connect(self.unix_socket)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/docker/client.py", line 116, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/docker/api/daemon.py", line 76, in version
    return self._result(self._get(url), json=True)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/docker/client.py", line 139, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dominik/.PyCharmCE2018.2/config/scratches/test_ai.py", line 5, in <module>
    env.configure(remotes=1) # creates a local docker container
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/gym/core.py", line 224, in configure
    self._configure(*args, **kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/universe/vectorized/core.py", line 39, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/gym/core.py", line 349, in _configure
    return self.env.configure(*args, **kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/gym/core.py", line 224, in configure
    self._configure(*args, **kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/universe/wrappers/render.py", line 18, in _configure
    super(Render, self)._configure(**kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/universe/vectorized/core.py", line 39, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/gym/core.py", line 349, in _configure
    return self.env.configure(*args, **kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/gym/core.py", line 224, in configure
    self._configure(*args, **kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/universe/wrappers/throttle.py", line 27, in _configure
    super(Throttle, self)._configure(**kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/universe/vectorized/core.py", line 39, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/gym/core.py", line 349, in _configure
    return self.env.configure(*args, **kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/gym/core.py", line 224, in configure
    self._configure(*args, **kwargs)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/universe/envs/vnc_env.py", line 199, in _configure
    use_recorder_ports=record,
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/universe/remotes/build.py", line 19, in build
    n=n,
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/universe/remotes/docker_remote.py", line 44, in __init__
    self._assigner = PortAssigner(reuse=reuse)
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/universe/remotes/docker_remote.py", line 162, in __init__
    self.client, self.info = get_client()
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/universe/remotes/docker_remote.py", line 156, in get_client
    return docker.Client(base_url=host, version=client_api_version), info
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/docker/client.py", line 99, in __init__
    self._version = self._retrieve_server_version()
  File "/home/dominik/PycharmProjects/GymAI/.ai/lib/python3.6/site-packages/docker/client.py", line 124, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
```

**Comment by Dominik1999** [comment]
Is it maybe a docker problem?

**Comment by harinij** [comment]
It appears that docker seems to be trying to connect but no perms. Try running the script with 'sudo' to give it perms.
